@extends('layouts.login-template', [
    'title' => 'Staff',
    'bgImage' => '/images/staff-login-bg.jpg',
    'btnColorToken' => '--color-primary',
    'btnColorOnToken' => '--color-on-primary',
    'btnHoverDark' => '#003d7a',
    'btnHoverLight' => '#0066cc',
    'spinnerColorToken' => '--color-on-primary',
    'idLabel' => 'Staff ID',
    'idPlaceholder' => 'e.g. 6767',
    'idRegex' => '^\d+$',
    'formatHint' => 'Numeric staff ID only',
    'loginType' => 'staff',
    'roleSwitchHtml' => 'Student? <a href="' . route('login.student') . '">Student Login</a>',
])
